name: metric-conv
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python==3.8
    - numpy==1.19.1
    - matplotlib==3.3.0
    - pytorch
    - torchvision
    - pandas==1.0.4
    - tqdm==4.46.1
    - trimesh==3.6.43
    - pyyaml
    - requests
    - pip
    - pip:
        - cmake
        - pytest==6.1.2
        - isort==5.6.4
        - black==20.8b1
        - openmesh
